version: '3'

services:
  db:
    container_name: pexp_db_1
    restart: always
    build:
      context: docker/mongo/
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: pexpD3V453R
      MONGODB_USERNAME: pexpDevUser
      MONGODB_PASSWORD: pexpD3V453R
      MONGODB_DATABASE: pexpDev
    volumes:
      - data:/bitnami/mongodb
    networks:
      - pexpnet

  mail:
    container_name: pexp_mail_1
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    networks:
      - pexpnet

  minio:
    container_name: pexp_minio_1
    restart: always
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12345678
    volumes:
      - minio:/data
    command: server /data
    networks:
      - pexpnet

  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: pexp_redis_1
    environment:
      - REDIS_PASSWORD=ewsua132435 # Security reasons
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG # Security reasons
    ports:
      - 6379:6379
    volumes:
      - data:/bitnami/redis/data
    networks:
      - pexpnet

networks:
  pexpnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
  minio:
    driver: "local"
